# This is a basic workflow to help you get started with Actions

name: cppcheck
on: [push, pull_request]
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install cppcheck
    - run: cppcheck --enable=all --suppress=missingInclude --suppress=unusedFunction --suppress=missingIncludeSystem --inline-suppr --std=c++17 --error-exitcode=10 src/*.cpp
